spring:
  profiles:
    active: dev
---
server:
  port: 8003
spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/yangou
      username: root
      password: 123456
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
mybatis-plus:
  mapper-locations: classpath:cn/itsource/yangou/mapper/*Mapper.xml
  type-aliases-package: cn.itsource.yangou.domain,cn.itsource.yangou.query
---
server:
  port: 8004
spring:
  application:
    name: PRODUCT-SERVICE-TEST
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/yangou_test
      username: root
      password: 123456
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
mybatis-plus:
  mapper-locations: classpath:cn/itsource/yangou/mapper/*Mapper.xml
  type-aliases-package: cn.itsource.yangou.domain,cn.itsource.yangou.query